name: flutter_application_login
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.1
  intl: ^0.20.1 #Es para que la fecha sea en español  
  cupertino_icons: ^1.0.2  
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  geolocator: ^13.0.2
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/
